### ISSUE TITLE
Conversion of Eye gaze coordinates(VR environment) to image index

### ISSUE THREAD

**Issue by nileshpd1211** [vsitzmann/vr-saliency#1]
Hi,
Could you kindly help me with converting the gaze data coordinates give  for the VR environment to image coordinates ( by image coordinates I mean ith and jth component of the img matrix).

Thanks a lot :)

**Comment by vsitzmann** [comment]
Hi,

in principle, the gaze coordinates are given as a pair of two angles - one for latitude (range 0 to 180 degrees) and one for longitude (range 0 to 360 degrees). Since the [equirectangular image](https://en.wikipedia.org/wiki/Equirectangular_projection) is simply indexed by latitude and longitude, you can convert latitude and longitude to image coordinates like so:

img_y = (latitude / 180) * img_height
img_x = (longitude / 360) * img_width

This is what the function "angle2img(lat_lon_array, img_height_width)" does. 

If you load the dataset as is done in section "Preload files into memory", the variable "runs_files" will be a list where each item of the list represents all the measurements for one scene. Each of these items then has a "data" element which is the data from that scene - so, to get all the experimental runs for scene 0, you would do runs_files[0]['data']. That will then be a list of pandas dataframes, where each pandas dataframe holds all the data of a single subject. Each of these then has a column "gaze_lot_lon" (see function "render_exploration_frames" for a reference how that is then used).

It's been a while since I looked at that code, so I hope this is all accurate. I hope that helps! Let me know if I can help you any further.

Best
Vincent

**Comment by nileshpd1211** [comment]
Thanks a lot for replying :D I was able to get the image coordinates.
